// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ud9JpUD8N987dWHx7H9cnr
import * as React from "react";
import { EmbedCss } from "@plasmicpkgs/plasmic-embed-css"; // plasmic-import: qF0uJxFztB/codeComponent

export default function GlobalContextsProvider(props) {
  const { children, embedCssProps } = props;
  return (
    <EmbedCss
      {...embedCssProps}
      css={
        embedCssProps && "css" in embedCssProps
          ? embedCssProps.css
          : "/* CSS snippet */\r\n.png-shadow {\r\n    -webkit-filter: drop-shadow(5px 5px 5px #222);\r\n    filter: drop-shadow(5px 5px 5px #222);\r\n}"
      }
    >
      {children}
    </EmbedCss>
  );
}
